version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      # PostgreSQL configuration
      SQL_USERNAME: jdbc:postgresql://dpg-cv1dabdds78s73docqvg-a/equity
      SQL_URL: equity_user
      SQL_PASSWORD: vS4b9ghFNUAbHjB7jQ63u9E59VAFjNGh
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      # Redis configuration
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

  redis:
    image: redis:6
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: 