spring:
  datasource:
    username: ${SQL_USERNAME:equity_user}
    url: ${SQL_URL:jdbc:postgresql://dpg-cv1dabdds78s73docqvg-a.frankfurt-postgres.render.com/equity}
    password: ${SQL_PASSWORD:vS4b9ghFNUAbHjB7jQ63u9E59VAFjNGh}
    driver-class-name: org.postgresql.Driver
  jpa:
    # database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
  application.name: market-guru
  data:
    redis:
      port: 6379
      password: ${SPRING_REDIS_PASSWORD:}
      ssl:
        enabled: ${SPRING_REDIS_SSL:false}
      host: ${SPRING_REDIS_HOST:red-cv1kqoaj1k6c7394qgig}
      database: 1
logging:
  level:
    org: info
    com: info
    root: info
  webmvc:
    cors:
      allowed-origins: https://market-guru-ui-353d.vercel.app
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: '*'
      allow-credentials: true

# JWT Properties
app:
  jwt:
    secret: YourVerySecretKeyHereMakeItAtLeast32BytesLongForBetterSecurity1234567890
    expiration: 86400000  # 1 day in milliseconds
    refresh-expiration: 604800000  # 7 days in milliseconds
