spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/indian_equity?useSSL=false&useUnicode=yes&characterEncoding=UTF-8&characterSetResults=UTF-8&createDatabaseIfNotExist=true
    password:
  application.name: market-guru
  data:
    redis:
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:}
      ssl:
        enabled: ${SPRING_REDIS_SSL:false}
      host: ${SPRING_REDIS_HOST:localhost}
      database: 1
logging:
  level:
    org: warn
    com: info
    root: warn
  webmvc:
    cors:
      allowed-origins: http://localhost:4173
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: '*'
      allow-credentials: true

# JWT Properties
app:
  jwt:
    secret: YourVerySecretKeyHereMakeItAtLeast32BytesLongForBetterSecurity1234567890
    expiration: 86400000  # 1 day in milliseconds
    refresh-expiration: 604800000  # 7 days in milliseconds
